---
- name: Install and configure LAMP stack on web servers
  hosts: web_servers
  become: yes
  tasks:
    - name: Update apt packages
      apt:
        update_cache: yes

    - name: Install Apache
      apt:
        name: apache2
        state: present

    - name: Install PHP and required modules
      apt:
        name:
          - php
          - libapache2-mod-php
          - php-mysql
        state: present

    - name: Install firewall utility (ufw)
      apt:
        name: ufw
        state: present

    - name: Allow HTTP and HTTPS traffic through the firewall
      ufw:
        rule: allow
        name: 'Apache Full'

    - name: Enable and start Apache service
      service:
        name: apache2
        state: started
        enabled: yes

    - name: Create a simple PHP info page
      copy:
        dest: /var/www/html/info.php
        content: |
          <?php
            phpinfo();
          ?>
        mode: '0644'

    - name: Restart Apache to apply changes
      service:
        name: apache2
        state: restarted

- name: Install and configure MySQL on database servers
  hosts: db_servers
  become: yes
  tasks:
    - name: Install MySQL server
      apt:
        name: mysql-server
        state: present

    - name: Start MySQL service
      service:
        name: mysql
        state: started
        enabled: yes

