---

- name: Configure Oracle user limits
  lineinfile:
    path: "/etc/security/limits.conf"
    line: "{{ item }}"
    create: yes
  loop:
    - "{{ oracle_user }} soft nofile 1024"
    - "{{ oracle_user }} hard nofile 65536"
    - "{{ oracle_user }} soft nproc 2047"
    - "{{ oracle_user }} hard nproc 16384"

